### ISSUE TITLE
Access to PGBoss deadLetter Option

### ISSUE THREAD

**Issue by RasikaLakmal** [wavezync/nestjs-pgboss#14]
When I tried to access the deadLetter option through the wavezync pgboss package, it already provided access to PgBoss, but I still couldn't access the deadLetter option. I updated the main pg-boss package to the latest version, and then I was able to access the deadLetter option.

In the wavezync package, the pg-boss version is v9.0.3, and it needs to be upgraded to the latest version, v10.1.1.

**Comment by kasvith** [comment]
@samaratungajs i think updating peer deps will help here
